#
# This Makefile was automatically generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
sysconst_mdl.f90 \
sampleSTAT.f90 \
samplestatistics_mdl.f90

SRCS_F90d1 = \
sng_mdl.F90 \
dbg_mdl.F90 \
sngall_mdl.F90

SRCS_mdd1 = \
README.md

SRCS_d1 = \
Makefile

OBJS_f90d1 = \
sysconst_mdl.o \
sampleSTAT.o \
samplestatistics_mdl.o

OBJS_F90d1 = \
sng_mdl.o \
dbg_mdl.o \
sngall_mdl.o

OBJS_mdd1 = \


OBJS_d1 = \


SRC_DIR_f90d1 =

SRC_DIR_F90d1 =

SRC_DIR_mdd1 =

SRC_DIR_d1 =
OBJS_DIR = obj/Release/
EXE_DIR = bin/Release/

EXE = sampleSTAT
FC = gfortran
IDIR =
CFLAGS = -Wall -O2   -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s -static-libgfortran
LIBS =

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_F90d1):$(OBJS_DIR):$(SRC_DIR_mdd1):$(OBJS_DIR):$(SRC_DIR_d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_F90d1) $(OBJS_mdd1) $(OBJS_d1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_F90d1) $(OBJS_mdd1) $(OBJS_d1)
	@mkdir -p $(EXE_DIR)
	$(FC) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_F90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_F90d1)$(@:.o=.F90) -o $(OBJS_DIR)$@

$(OBJS_mdd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_mdd1)$(@:.o=.md) -o $(OBJS_DIR)$@

$(OBJS_d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_d1)$(@:.o=.) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
sysconst_mdl.o: \
    sysconst_mdl.f90
sampleSTAT.o: \
    sampleSTAT.f90 \
    samplestatistics_mdl.o \
    sngall_mdl.o \
    sysconst_mdl.o
sng_mdl.o: \
    sng_mdl.F90 \
    dbg_mdl.o
dbg_mdl.o: \
    dbg_mdl.F90
samplestatistics_mdl.o: \
    samplestatistics_mdl.f90 \
    sysconst_mdl.o
sngall_mdl.o: \
    sngall_mdl.F90 \
    dbg_mdl.o \
    sng_mdl.o
install :
	cp ./bin/Release/sampleSTAT /usr/local/bin
