#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_F90d1 = \
dbg_mdl.F90 \
sng_mdl.F90 \
sngall_mdl.F90 

SRCS_f90d1 = \
readdata_mdl.f90 \
sampleSTAT.f90 \
samplestatistics_mdl.f90 \
sysconst_mdl.f90 

OBJS_F90d1 = \
dbg_mdl.o \
sng_mdl.o \
sngall_mdl.o 

OBJS_f90d1 = \
readdata_mdl.o \
sampleSTAT.o \
samplestatistics_mdl.o \
sysconst_mdl.o 

SRC_DIR_F90d1 = 

SRC_DIR_f90d1 = 
OBJS_DIR = ../../CB-Workspaces/sampleSTAT/obj/Release/f90/sampleSTAT/
EXE_DIR = ../../CB-Workspaces/sampleSTAT/bin/Release/

EXE = sampleSTAT
FC = gfortran
LD = gfortran
IDIR = 
CFLAGS = -Wall -O2  -J$(OBJS_DIR) $(IDIR)
LFLAGS = -s -static 
LIBS = 

VPATH = $(SRC_DIR_F90d1):$(OBJS_DIR):$(SRC_DIR_f90d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_F90d1) $(OBJS_f90d1))

all : $(EXE)

$(EXE) : $(OBJS_F90d1) $(OBJS_f90d1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_F90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_F90d1)$(@:.o=.F90) -o $(OBJS_DIR)$@

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# File dependencies
dbg_mdl.o: \
    dbg_mdl.F90
readdata_mdl.o: \
    readdata_mdl.f90 \
    sysconst_mdl.o
sampleSTAT.o: \
    sampleSTAT.f90 \
    readdata_mdl.o \
    samplestatistics_mdl.o \
    sngall_mdl.o \
    sysconst_mdl.o
samplestatistics_mdl.o: \
    samplestatistics_mdl.f90 \
    sysconst_mdl.o
sng_mdl.o: \
    sng_mdl.F90 \
    dbg_mdl.o
sngall_mdl.o: \
    sngall_mdl.F90 \
    dbg_mdl.o \
    sng_mdl.o
sysconst_mdl.o: \
    sysconst_mdl.f90

